
MoleculeTable:
  - name: Amino acids
    symbol: brick
    daltons: 100
  - name: ATP
    symbol: bang
    daltons: 507.18
  - name: ADP
    symbol: briefcase
    daltons: 423.7
  - name: Phosphate
    symbol: P
    daltons: 94.97
  - name: X
    symbol: X
    daltons: 500
  - name: R
    symbol: R
    daltons: 1000
  - name: ATP Synthase
    symbol: hammer
    daltons: 5e5
    half-life-hours: 1
    num-amino-acids: 5e3
  - name: ATP Consumer
    symbol: gear
    daltons: 1e6
    num-amino-acids: 5e3
  - name: Ribosome
    symbol: factory
    daltons: 2.7e6
    num-amino-acids: 7459
    

ReactionTable:
  - formula: ADP + Phosphate -> ATP
    protein: ATP Synthase
    kcat: 1e-3
    KMs:
      ADP: 1e-1
      Phosphate: 1e-2
  - formula: 2 X + ATP -> R + ADP + Phosphate
    protein: ATP Consumer
    kcat: 1e-2
    KMs:
      X: 1e-1
      ATP: 1e-3


BiomeTable:
  - name: Alkaline Vents
    concentrations:
      Amino acids: 100  # Above the ribosomal KM for AAs.
      Phosphate: 1
      
# This is pretty janky but I guess will do for now.
# Eventually this shouldn't be YAML, just a small DSL that is compiled into C++ objects representing the expressions.
# if, else, =, +=, <, >.
DNA:
  - if: ATP Synthase < 300
    then:
      - ATP Synthase += 1.0
  - if: ATP Synthase < 200
    then:
      - all = 0.0
      - ATP Synthase = 1.0
  - if: Ribosome > 30000
    then:
      - Ribosome = 0.0
  - if: Ribosome < 30000
    then:
      - Ribosome = 1.0
  - if: Ribosome < 20000
    then:
      - Ribosome = 2.0
  - if: Ribosome < 10000
    then:
      - Ribosome = 3.0
  # - if: Ribosomes > 7e4
  #   then:
  #     - divide()