# TODO: Protein half-lives are typically 0.25 - 2 hours, which a bunch much longer than 3 hours.
# See http://book.bionumbers.org/how-fast-do-rnas-and-proteins-degrade/

MoleculeTable:
  - name: Amino acids
    symbol: brick
    daltons: 100
  - name: ATP
    symbol: bang
    daltons: 507.18
  - name: ADP
    symbol: briefcase
    daltons: 423.7
  - name: Phosphate
    symbol: P
    daltons: 94.97
  - name: Starch
    symbol: S
    daltons: 18015.6  # Uh, 100 glucoses?  I don't have a way to represent polymers rn.
  - name: Glucose
    symbol: G
    daltons: 180.156
  - name: ATP Synthase
    symbol: hammer
    num-amino-acids: 5e3
    half-life-hours: 20  # https://www.researchgate.net/figure/Half-life-calculation-for-three-subunits-of-the-mitochondrial-ATP-synthase-in-response-to_fig12_334548965
  - name: Amylase
    num-amino-acids: 496
    half-life-hours: 10
  - name: Ribosome
    symbol: factory
    num-amino-acids: 12600  # https://bscb.org/learning-resources/softcell-e-learning/ribosome/.  4.2Mda, 1/3 protein.
    half-life-hours: 100
  - name: Proteasome
    num-amino-acids: 2e4  # figure 2 of http://book.bionumbers.org/how-fast-do-proteasomes-degrade-proteins/ 
    half-life-hours: 60  # http://book.bionumbers.org/how-fast-do-proteasomes-degrade-proteins/

ReactionTable:
  - formula: Glucose + 30 ADP + 30 Phosphate -> 30 ATP
    protein: ATP Synthase
    kcat: 3  # https://www.varsitytutors.com/biochemistry-help/atp-synthase
    KMs:
      Glucose: 1e-1
      ADP: 1e-2
      Phosphate: 1e-2
  - formula: Starch -> 100 Glucose  # no ATP needed.
    protein: Amylase
    kcat: 9.21  # https://www.sciencedirect.com/science/article/pii/S1046592816300547
    KMs:
      Starch: 2.86  # https://www.sciencedirect.com/science/article/pii/S1046592816300547

BiomeTable:
  - name: Petri dish
    m3: 1e-5
    concentrations:
      Amino acids: 1
      Starch: 50
      
# This is pretty janky but I guess will do for now.
# Eventually this shouldn't be YAML, just a small DSL that is compiled into C++ objects representing the expressions.
# if, else, =, +=, <, >.
# Also it's weird to use "X" for the concentration of something in the if statement, and then "X" for the TF target.
# They're totally different things.
DNA:
  - if: Ribosome > 30000
    then:
      - Ribosome = 0.0
  - if: ATP Synthase > 30000
    then:
      - ATP Synthase = 0.0
  - if: Amylase > 30000
    then:
      - Amylase = 0.0
  - if: Proteasome > 30000
    then:
      - Proteasome = 0.0
  # - if: Ribosomes > 7e4
  #   then:
  #     - divide()



  # - formula: 2 X + ATP -> R + ADP + Phosphate
  #   protein: ATP Consumer
  #   kcat: 1e-2
  #   KMs:
  #     X: 1e-1
  #     ATP: 1e-3
    # - name: ATP Consumer
    # symbol: gear
    # num-amino-acids: 5e3
  # - name: X
  #   symbol: X
  #   daltons: 500
  # - name: R
  #   symbol: R
  #   daltons: 1000
